### ISSUE TITLE
RAII Way deregistration could cause redundant call to remove_handler

### ISSUE THREAD

**Issue by xubury** [ptsouchlos/eventbus#28]
So `handler_registration`  deregister itself when out of scope. 
But if you call `remove_handler` on a `handler_registration` before, the deregistration in destructor seems redundant.
Maybe it is a good idea to reset `handler_registration`'s member to `nullptr` when using `remove_handler`?

**Comment by ptsouchlos** [comment]
This is a simple enough change that I might as well do it. Thanks for pointing that out!

**Comment by ptsouchlos** [comment]
Should be fixed in 275e0cff588c1d89bb148c30c1f4d8c10f179f34
